steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/agentsea-dev/agent-desk/ui:$COMMIT_SHA",
        "-f",
        "Dockerfile",
        "./ui/agentdesk",
      ]
  # Build the second image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image-2:$COMMIT_SHA', '-f', 'docker/Dockerfile2', '.']

images:
  - "us-central1-docker.pkg.dev/agentsea-dev/agent-desk/ui:$COMMIT_SHA"

timeout: "1200s"
